### ISSUE TITLE
Legal text is not printing correctly – breaking the license

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#941]
Print.css of the legaltext pages of at least the 4.0 suite is not working correctly.

Steps to reproduce
Go to a legal code page of a 4.0 license (e.g. [CC BY-SA 4.0 – English](https://creativecommons.org/licenses/by-sa/4.0/legalcode) ).
Scroll down and note that the first indent of a section is number a,b,c (eg. Section 6(b) )
Print the page using your browser. 
Look at the print
Note that the first indent of a section is now numbered 1,2,3, (eg. Section 6(1). However we refer to the sections by the former method (e.g. Section 6(b) ).

This makes the license no longer work properly.

Attached is a pdf with the problem.

This could also happen with the other license versions,.

[Creative Commons — Attribution-ShareAlike 4.0 International — CC BY-SA 4.0.pdf](https://github.com/creativecommons/creativecommons.org/files/3010043/Creative.Commons.Attribution-ShareAlike.4.0.International.CC.BY-SA.4.0.pdf)

**Comment by peterspdx** [comment]
assigned to @TimidRobot with a copy to @kgodey.  Thanks, Maarten.

**Comment by kgodey** [comment]
TODO: This seems like a duplicate of https://github.com/creativecommons/creativecommons.org investigate and close it if needed.

**Comment by mzeinstra** [comment]
I believe the two are separate. Looking 'odd' is not the same as 'messes up internal textual references' that could possibly have legal consequences for the license (when printed).

**Comment by TimidRobot** [comment]
Within the [creativecommons/new-creativecommons.org](https://github.com/creativecommons/new-creativecommons.org) repository:

[`/docroot/includes/legalcode.css`](https://github.com/creativecommons/new-creativecommons.org/blob/1be0daa22c5cd5d590c5423ff0bbe249ce6659c7/docroot/includes/legalcode.css#L313) contains:
```css
/* Please read:
   - https://www.w3schools.com/tags/att_ol_type.asp
   - https://stackoverflow.com/questions/27104096/css-selector-type-var-not-selecting-lower-alpha-versus-upper-alpha
*/
#deed-main ol[type="a"] { list-style-type: lower-alpha; }
/*#deed-main ol[type="A"] { list-style-type: upper-alpha; } no case-sensitive :( */
#deed-main ol[type="a"] ol[type="a"] { list-style-type: upper-alpha; } /* crappy solution */
#deed-main ol[type="i"] { list-style-type: lower-roman; }
/*#deed-main ol[type="I"] { list-style-type: upper-roman; } no case-sensitive :( */
#deed-main ol[type="i"] ol[type="i"] { list-style-type: upper-roman; } /* crappy solution */
```
However, [`/docroot/includes/legalcode-print.css`](https://github.com/creativecommons/new-creativecommons.org/blob/master/docroot/includes/legalcode-print.css) does not
